### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tpritc** [densylkin/Unity-RTS_Camera#1]
Denis, I've really enjoyed using RTS_Camera. I appreciate all of the work you've put into it. I'm using it in an educational setting and I was wondering what open source license you are distributing the code under, since I couldn't find that in the repo.

**Comment by densylkin** [comment]
Oh, forgot to add license file. RTS camera is licensed under MIT license.

**Comment by tpritc** [comment]
Thanks for the info! I'll close this issue now.
