### ISSUE TITLE
Do you accept PRs?

### ISSUE THREAD

**Issue by ghost** [densylkin/Unity-RTS_Camera#4]
Hi, awesome plugin, but was wondering if you are currently accepting PRs and re-submitting updated versions to the store.

If not, I'll go ahead and fork this.

**Comment by densylkin** [comment]
Hi, i'm not interested in futher development of this package and asset store submission. So if you're making any major changes better fork it but i'll accept bugfixes

**Comment by ghost** [comment]
Got it, thanks for the reply!

**Comment by ghost** [comment]
@densylkin One last thing, what license do you release the code under?

**Comment by densylkin** [comment]
MIT
