### ISSUE TITLE
Auto height Raycast wrong

### ISSUE THREAD

**Issue by SaphuA** [densylkin/Unity-RTS_Camera#7]
https://github.com/densylkin/RTS_Camera/blob/586730cc489cef26b8437c65122a6d3d361fda2e/RTS_Camera/Assets/RTS_Camera/Scripts/RTS_Camera.cs#L336

The parameters put into the raycast method are wrong. Should be changed to:

`if (Physics.Raycast(ray, out hit, Mathf.Infinity, groundMask.value))`

**Comment by neoascetic** [comment]
Why was that closed? It is definitely wrong.
